# These are supported funding model platforms
# You can add your funding links here

github: itxRishabh
# patreon: your_patreon
# open_collective: your_opencollective
# ko_fi: your_kofi
# custom: ['https://your-website.com/donate']
